"""add calls, stories, and e2ee fields

Revision ID: 48fc738698de
Revises: 5ab68f67333b
Create Date: 2026-07-11 03:29:18.923789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48fc738698de'
down_revision: Union[str, None] = '5ab68f67333b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_links',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('requires_admin_approval', sa.Boolean(), nullable=False),
    sa.Column('room_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_call_links_created_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_links')),
    sa.UniqueConstraint('room_key', name=op.f('uq_call_links_room_key'))
    )
    op.create_table('stories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('text', 'image', 'video', name='storytype', native_enum=False, length=20), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('background_color', sa.String(length=20), nullable=True),
    sa.Column('media_url', sa.String(length=1024), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_stories_author_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories'))
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index('ix_stories_author_id', ['author_id'], unique=False)
        batch_op.create_index('ix_stories_expires_at', ['expires_at'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('call_link_id', sa.Uuid(), nullable=True),
    sa.Column('initiator_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('voice', 'video', name='calltype', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('ringing', 'active', 'ended', 'missed', 'declined', name='callstatus', native_enum=False, length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_link_id'], ['call_links.id'], name=op.f('fk_calls_call_link_id_call_links'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_calls_conversation_id_conversations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], name=op.f('fk_calls_initiator_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls'))
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index('ix_calls_conversation_id', ['conversation_id'], unique=False)
        batch_op.create_index('ix_calls_initiator_id', ['initiator_id'], unique=False)

    op.create_table('story_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('viewer_id', sa.Uuid(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_story_views_story_id_stories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewer_id'], ['users.id'], name=op.f('fk_story_views_viewer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_views'))
    )
    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.create_index('ix_story_views_story_id', ['story_id'], unique=False)

    op.create_table('call_participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_participants_call_id_calls'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_call_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_participants'))
    )
    with op.batch_alter_table('call_participants', schema=None) as batch_op:
        batch_op.create_index('ix_call_participants_call_id', ['call_id'], unique=False)

    op.create_table('message_recipient_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('wrapped_key', sa.Text(), nullable=False),
    sa.Column('wrap_iv', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_message_recipient_keys_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_message_recipient_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message_recipient_keys')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_message_recipient_keys_message_user')
    )
    with op.batch_alter_table('message_recipient_keys', schema=None) as batch_op:
        batch_op.create_index('ix_message_recipient_keys_message_id', ['message_id'], unique=False)
        batch_op.create_index('ix_message_recipient_keys_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_encrypted', sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(sa.Column('iv', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('public_key')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('iv')
        batch_op.drop_column('is_encrypted')

    with op.batch_alter_table('message_recipient_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_message_recipient_keys_user_id')
        batch_op.drop_index('ix_message_recipient_keys_message_id')

    op.drop_table('message_recipient_keys')
    with op.batch_alter_table('call_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_call_participants_call_id')

    op.drop_table('call_participants')
    with op.batch_alter_table('story_views', schema=None) as batch_op:
        batch_op.drop_index('ix_story_views_story_id')

    op.drop_table('story_views')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index('ix_calls_initiator_id')
        batch_op.drop_index('ix_calls_conversation_id')

    op.drop_table('calls')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index('ix_stories_expires_at')
        batch_op.drop_index('ix_stories_author_id')

    op.drop_table('stories')
    op.drop_table('call_links')
    # ### end Alembic commands ###
