"""Deterministic demo data for SQLite assignment seeding."""

DEMO_PASSWORD = "password123"

SEED_USERS = [
    {
        "username": "alice",
        "email": "alice@example.com",
        "display_name": "Alice Morgan",
        "avatar_url": "/avatars/avatar-1.svg",
        "status": "online",
        "last_seen_minutes": 1,
    },
    {
        "username": "bob",
        "email": "bob@example.com",
        "display_name": "Bob Chen",
        "avatar_url": "/avatars/avatar-2.svg",
        "status": "away",
        "last_seen_minutes": 18,
    },
    {
        "username": "charlie",
        "email": "charlie@example.com",
        "display_name": "Charlie Brooks",
        "avatar_url": "/avatars/avatar-3.svg",
        "status": "online",
        "last_seen_minutes": 4,
    },
    {
        "username": "diana",
        "email": "diana@example.com",
        "display_name": "Diana Patel",
        "avatar_url": "/avatars/avatar-4.svg",
        "status": "busy",
        "last_seen_minutes": 42,
    },
    {
        "username": "eve",
        "email": "eve@example.com",
        "display_name": "Eve Wilson",
        "avatar_url": "/avatars/avatar-5.svg",
        "status": "offline",
        "last_seen_minutes": 240,
    },
    {
        "username": "frank",
        "email": "frank@example.com",
        "display_name": "Frank Rivera",
        "avatar_url": "/avatars/avatar-6.svg",
        "status": "offline",
        "last_seen_minutes": 720,
    },
    {
        "username": "grace",
        "email": "grace@example.com",
        "display_name": "Grace Kim",
        "avatar_url": "/avatars/avatar-1.svg",
        "status": "online",
        "last_seen_minutes": 7,
    },
]

SEED_CONTACTS = [
    ("alice", "bob"),
    ("alice", "charlie"),
    ("alice", "diana"),
    ("alice", "eve"),
    ("bob", "charlie"),
    ("bob", "frank"),
    ("charlie", "diana"),
    ("diana", "eve"),
    ("eve", "grace"),
    ("frank", "grace"),
]

SEED_CONVERSATIONS = [
    {"key": "direct-alice-bob", "type": "direct", "members": ["alice", "bob"]},
    {"key": "direct-alice-charlie", "type": "direct", "members": ["alice", "charlie"]},
    {"key": "direct-alice-diana", "type": "direct", "members": ["alice", "diana"]},
    {"key": "direct-bob-eve", "type": "direct", "members": ["bob", "eve"]},
    {
        "key": "group-beacon-launch",
        "type": "group",
        "name": "Beacon Launch Team",
        "avatar_url": "/avatars/avatar-6.svg",
        "members": ["alice", "bob", "charlie", "diana", "eve", "grace"],
    },
]

MESSAGE_TOPICS = [
    "Morning team, I added the final notes to the launch checklist.",
    "Thanks, I will review the onboarding copy after standup.",
    "The SQLite migration path looks clean on a fresh database now.",
    "Great. I also checked the mobile inbox spacing on Vercel.",
    "Can someone confirm the demo credentials are in the README?",
    "Confirmed. Alice, Bob, Charlie, Diana, and Eve all use the same demo password.",
    "I like that the seeded inbox has both direct chats and a launch group.",
    "Same here. It makes the first login feel much more complete.",
    "I tested the message history endpoint with the seeded conversations.",
    "Nice. Did the read and delivered states come through?",
    "Yes, each participant gets a status row for every seeded message.",
    "The group thread feels realistic enough for a classroom demo.",
    "Let us keep registration enabled in case reviewers want to create another user.",
    "Agreed. The seeded accounts should be the main path though.",
    "I am checking WebSocket auth next with Alice's token.",
    "Perfect. The realtime route should keep working because auth still uses JWT.",
    "Can we pin the launch group for Alice so it is visible immediately?",
    "Already done. Alice and the conversation creator get useful defaults.",
    "The latest Railway start command runs Alembic before Uvicorn.",
    "Good. Startup also runs migrations now, so it is protected either way.",
    "I added a few contact pairs so the people picker is not empty.",
    "That helps a lot. The demo should not feel like a blank shell.",
    "Do we need media attachments for the first pass?",
    "Not required for auth, but a couple seeded attachment rows show the model works.",
    "The assignment mostly wants sample users, conversations, and messages.",
    "Exactly. The core login and inbox path is the priority.",
    "I will do one final fresh database smoke test after this.",
    "Please include conversation list and message loading in that check.",
    "Will do. I will also verify refresh and /me.",
    "Great. That gives us an end-to-end confidence pass.",
    "The seeded data should remain idempotent across restarts.",
    "Yes. Existing users are updated and existing conversations are reused.",
    "No duplicate messages after repeated startup runs?",
    "Correct. Messages are skipped when a conversation already has history.",
    "This should make the Railway demo much smoother.",
    "Agreed. Reviewers can just log in and see activity immediately.",
    "I am going to use Alice for the default smoke test.",
    "Alice is a good default because she belongs to four seeded conversations.",
    "Everything is lining up nicely now.",
    "Ship it once the tests are green.",
]
